name: radar_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pytorch
  - open3d
  - tqdm
  - jupyter
  - pip
  - h5py
  - joblib
  - lightgbm
  - pip:
      - pyntcloud
      - PySide6
