[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "radar-utils"
version = "0.1.0"
dependencies = ["pandas", "numpy"]

[tool.setuptools.packages.find]
where = ["src"]
