name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: environment.yaml
          activate-environment: radar_env
          python-version: 3.10

      - name: Run flake8
        shell: bash -l {0}
        run: |
          flake8 . || true
